security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  providers:
    our_db_provider:
      entity:
        class: App\Entity\User
        property: mail
        # if you're using multiple entity managers
        # manager_name: customer
    in_memory: { memory: ~ }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      lazy: true
      provider: our_db_provider
      logout:
        path: app_logout
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator

  # Dans la partie access_control nous définissons les routes protégées
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }
# La partie role_hierarchy contient la hiérarchie des rôles
# Un éditeur sera également utilisateur
# Un administrateur sera également éditeur et donc utilisateur
# role_hierarchy:
#   ROLE_ADMIN: ROLE_USER
